FROM node:22-slim

RUN apt-get update && apt-get install -y --fix-missing postgresql-client && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
COPY stockfish /usr/bin/stockfish
RUN chmod +x /usr/bin/stockfish

ENV HOST=0.0.0.0
ENV PORT=3000
ENV STOCKFISH_PATH=/usr/bin/stockfish
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["npm", "run", "dev"]
