ALTER TABLE games ADD COLUMN IF NOT EXISTS "whiteTimeMs" INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS "blackTimeMs" INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS "lastMoveAt" TIMESTAMP WITH TIME ZONE;
